
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Willover Aviation Companies
tagline: "we are aircraft, inside and out"
email: ivan@willover.world
description: Willover Aviation deals with Aircraft maintenance, Avionics, AMETA training and Cargo hauling.
baseurl: "/" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
github_username:  cybersteam

# Build settings
markdown: kramdown
theme: minima
#I added this..:
plugins: [jekyll-sitemap]
plugins:
  - jekyll-feed

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
